# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{aprovafacil-ruby}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rafael Lima"]
  s.date = %q{2010-07-27}
  s.description = %q{Biblioteca Ruby para utilizacao do sistema AprovaFacil do Cobre Bem}
  s.email = %q{contato@rafael.adm.br}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.mkdn"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.mkdn",
     "Rakefile",
     "VERSION",
     "aprovafacil-ruby.gemspec",
     "lib/aprovafacil-ruby.rb",
     "lib/hash_strip_values.rb",
     "spec/aprovafacil-ruby_spec.rb",
     "spec/fixtures/cancelamento_marcado_erro.xml",
     "spec/fixtures/cancelamento_marcado_sucesso.xml",
     "spec/fixtures/cancelamento_online_erro.xml",
     "spec/fixtures/cancelamento_online_sucesso.xml",
     "spec/fixtures/config.yml",
     "spec/fixtures/dirty_data_structure.xml",
     "spec/fixtures/dummy-config.yml",
     "spec/fixtures/resultado_apc_erro.xml",
     "spec/fixtures/resultado_apc_sucesso.xml",
     "spec/fixtures/resultado_cap_erro.xml",
     "spec/fixtures/resultado_cap_sucesso.xml",
     "spec/hash_strip_values_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/rafaelp/aprovafacil-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby wrapper for AprovaFacil from Cobre Bem}
  s.test_files = [
    "spec/aprovafacil-ruby_spec.rb",
     "spec/hash_strip_values_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_runtime_dependency(%q<xml-simple>, [">= 1.0.12"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_dependency(%q<xml-simple>, [">= 1.0.12"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
    s.add_dependency(%q<xml-simple>, [">= 1.0.12"])
  end
end

